package net.minecraft.server;

public class Blocks
{
    public static final Block AIR;
    public static final Block STONE;
    public static final BlockGrass GRASS;
    public static final Block DIRT;
    public static final Block COBBLESTONE;
    public static final Block WOOD;
    public static final Block SAPLING;
    public static final Block BEDROCK;
    public static final BlockFluids WATER;
    public static final Block STATIONARY_WATER;
    public static final BlockFluids LAVA;
    public static final Block STATIONARY_LAVA;
    public static final BlockSand SAND;
    public static final Block GRAVEL;
    public static final Block GOLD_ORE;
    public static final Block IRON_ORE;
    public static final Block COAL_ORE;
    public static final Block LOG;
    public static final Block LOG2;
    public static final BlockLeaves LEAVES;
    public static final BlockLeaves LEAVES2;
    public static final Block SPONGE;
    public static final Block GLASS;
    public static final Block LAPIS_ORE;
    public static final Block LAPIS_BLOCK;
    public static final Block DISPENSER;
    public static final Block SANDSTONE;
    public static final Block NOTE_BLOCK;
    public static final Block BED;
    public static final Block GOLDEN_RAIL;
    public static final Block DETECTOR_RAIL;
    public static final BlockPiston PISTON_STICKY;
    public static final Block WEB;
    public static final BlockLongGrass LONG_GRASS;
    public static final BlockDeadBush DEAD_BUSH;
    public static final BlockPiston PISTON;
    public static final BlockPistonExtension PISTON_EXTENSION;
    public static final Block WOOL;
    public static final BlockPistonMoving PISTON_MOVING;
    public static final BlockFlowers YELLOW_FLOWER;
    public static final BlockFlowers RED_ROSE;
    public static final BlockPlant BROWN_MUSHROOM;
    public static final BlockPlant RED_MUSHROOM;
    public static final Block GOLD_BLOCK;
    public static final Block IRON_BLOCK;
    public static final BlockStepAbstract DOUBLE_STEP;
    public static final BlockStepAbstract STEP;
    public static final Block BRICK;
    public static final Block TNT;
    public static final Block BOOKSHELF;
    public static final Block MOSSY_COBBLESTONE;
    public static final Block OBSIDIAN;
    public static final Block TORCH;
    public static final BlockFire FIRE;
    public static final Block MOB_SPAWNER;
    public static final Block WOOD_STAIRS;
    public static final BlockChest CHEST;
    public static final BlockRedstoneWire REDSTONE_WIRE;
    public static final Block DIAMOND_ORE;
    public static final Block DIAMOND_BLOCK;
    public static final Block WORKBENCH;
    public static final Block CROPS;
    public static final Block SOIL;
    public static final Block FURNACE;
    public static final Block BURNING_FURNACE;
    public static final Block SIGN_POST;
    public static final Block WOODEN_DOOR;
    public static final Block LADDER;
    public static final Block RAILS;
    public static final Block COBBLESTONE_STAIRS;
    public static final Block WALL_SIGN;
    public static final Block LEVER;
    public static final Block STONE_PLATE;
    public static final Block IRON_DOOR_BLOCK;
    public static final Block WOOD_PLATE;
    public static final Block REDSTONE_ORE;
    public static final Block GLOWING_REDSTONE_ORE;
    public static final Block REDSTONE_TORCH_OFF;
    public static final Block REDSTONE_TORCH_ON;
    public static final Block STONE_BUTTON;
    public static final Block SNOW;
    public static final Block ICE;
    public static final Block SNOW_BLOCK;
    public static final Block CACTUS;
    public static final Block CLAY;
    public static final Block SUGAR_CANE_BLOCK;
    public static final Block JUKEBOX;
    public static final Block FENCE;
    public static final Block PUMPKIN;
    public static final Block NETHERRACK;
    public static final Block SOUL_SAND;
    public static final Block GLOWSTONE;
    public static final BlockPortal PORTAL;
    public static final Block JACK_O_LANTERN;
    public static final Block CAKE_BLOCK;
    public static final BlockRepeater DIODE_OFF;
    public static final BlockRepeater DIODE_ON;
    public static final Block TRAP_DOOR;
    public static final Block MONSTER_EGGS;
    public static final Block SMOOTH_BRICK;
    public static final Block BIG_MUSHROOM_1;
    public static final Block BIG_MUSHROOM_2;
    public static final Block IRON_FENCE;
    public static final Block THIN_GLASS;
    public static final Block MELON;
    public static final Block PUMPKIN_STEM;
    public static final Block MELON_STEM;
    public static final Block VINE;
    public static final Block FENCE_GATE;
    public static final Block BRICK_STAIRS;
    public static final Block STONE_STAIRS;
    public static final BlockMycel MYCEL;
    public static final Block WATER_LILY;
    public static final Block NETHER_BRICK;
    public static final Block NETHER_FENCE;
    public static final Block NETHER_BRICK_STAIRS;
    public static final Block NETHER_WART;
    public static final Block ENCHANTMENT_TABLE;
    public static final Block BREWING_STAND;
    public static final BlockCauldron CAULDRON;
    public static final Block ENDER_PORTAL;
    public static final Block ENDER_PORTAL_FRAME;
    public static final Block WHITESTONE;
    public static final Block DRAGON_EGG;
    public static final Block REDSTONE_LAMP_OFF;
    public static final Block REDSTONE_LAMP_ON;
    public static final BlockStepAbstract WOOD_DOUBLE_STEP;
    public static final BlockStepAbstract WOOD_STEP;
    public static final Block COCOA;
    public static final Block SANDSTONE_STAIRS;
    public static final Block EMERALD_ORE;
    public static final Block ENDER_CHEST;
    public static final BlockTripwireHook TRIPWIRE_SOURCE;
    public static final Block TRIPWIRE;
    public static final Block EMERALD_BLOCK;
    public static final Block SPRUCE_WOOD_STAIRS;
    public static final Block BIRCH_WOOD_STAIRS;
    public static final Block JUNGLE_WOOD_STAIRS;
    public static final Block COMMAND;
    public static final BlockBeacon BEACON;
    public static final Block COBBLE_WALL;
    public static final Block FLOWER_POT;
    public static final Block CARROTS;
    public static final Block POTATOES;
    public static final Block WOOD_BUTTON;
    public static final Block SKULL;
    public static final Block ANVIL;
    public static final Block TRAPPED_CHEST;
    public static final Block GOLD_PLATE;
    public static final Block IRON_PLATE;
    public static final BlockRedstoneComparator REDSTONE_COMPARATOR_OFF;
    public static final BlockRedstoneComparator REDSTONE_COMPARATOR_ON;
    public static final BlockDaylightDetector DAYLIGHT_DETECTOR;
    public static final Block REDSTONE_BLOCK;
    public static final Block QUARTZ_ORE;
    public static final BlockHopper HOPPER;
    public static final Block QUARTZ_BLOCK;
    public static final Block QUARTZ_STAIRS;
    public static final Block ACTIVATOR_RAIL;
    public static final Block DROPPER;
    public static final Block STAINED_HARDENED_CLAY;
    public static final Block HAY_BLOCK;
    public static final Block WOOL_CARPET;
    public static final Block HARDENED_CLAY;
    public static final Block COAL_BLOCK;
    public static final Block PACKED_ICE;
    public static final Block ACACIA_STAIRS;
    public static final Block DARK_OAK_STAIRS;
    public static final BlockTallPlant DOUBLE_PLANT;
    public static final BlockStainedGlass STAINED_GLASS;
    public static final BlockStainedGlassPane STAINED_GLASS_PANE;
    
    static {
        AIR = (Block)Block.REGISTRY.get("air");
        STONE = (Block)Block.REGISTRY.get("stone");
        GRASS = (BlockGrass)Block.REGISTRY.get("grass");
        DIRT = (Block)Block.REGISTRY.get("dirt");
        COBBLESTONE = (Block)Block.REGISTRY.get("cobblestone");
        WOOD = (Block)Block.REGISTRY.get("planks");
        SAPLING = (Block)Block.REGISTRY.get("sapling");
        BEDROCK = (Block)Block.REGISTRY.get("bedrock");
        WATER = (BlockFluids)Block.REGISTRY.get("flowing_water");
        STATIONARY_WATER = (Block)Block.REGISTRY.get("water");
        LAVA = (BlockFluids)Block.REGISTRY.get("flowing_lava");
        STATIONARY_LAVA = (Block)Block.REGISTRY.get("lava");
        SAND = (BlockSand)Block.REGISTRY.get("sand");
        GRAVEL = (Block)Block.REGISTRY.get("gravel");
        GOLD_ORE = (Block)Block.REGISTRY.get("gold_ore");
        IRON_ORE = (Block)Block.REGISTRY.get("iron_ore");
        COAL_ORE = (Block)Block.REGISTRY.get("coal_ore");
        LOG = (Block)Block.REGISTRY.get("log");
        LOG2 = (Block)Block.REGISTRY.get("log2");
        LEAVES = (BlockLeaves)Block.REGISTRY.get("leaves");
        LEAVES2 = (BlockLeaves)Block.REGISTRY.get("leaves2");
        SPONGE = (Block)Block.REGISTRY.get("sponge");
        GLASS = (Block)Block.REGISTRY.get("glass");
        LAPIS_ORE = (Block)Block.REGISTRY.get("lapis_ore");
        LAPIS_BLOCK = (Block)Block.REGISTRY.get("lapis_block");
        DISPENSER = (Block)Block.REGISTRY.get("dispenser");
        SANDSTONE = (Block)Block.REGISTRY.get("sandstone");
        NOTE_BLOCK = (Block)Block.REGISTRY.get("noteblock");
        BED = (Block)Block.REGISTRY.get("bed");
        GOLDEN_RAIL = (Block)Block.REGISTRY.get("golden_rail");
        DETECTOR_RAIL = (Block)Block.REGISTRY.get("detector_rail");
        PISTON_STICKY = (BlockPiston)Block.REGISTRY.get("sticky_piston");
        WEB = (Block)Block.REGISTRY.get("web");
        LONG_GRASS = (BlockLongGrass)Block.REGISTRY.get("tallgrass");
        DEAD_BUSH = (BlockDeadBush)Block.REGISTRY.get("deadbush");
        PISTON = (BlockPiston)Block.REGISTRY.get("piston");
        PISTON_EXTENSION = (BlockPistonExtension)Block.REGISTRY.get("piston_head");
        WOOL = (Block)Block.REGISTRY.get("wool");
        PISTON_MOVING = (BlockPistonMoving)Block.REGISTRY.get("piston_extension");
        YELLOW_FLOWER = (BlockFlowers)Block.REGISTRY.get("yellow_flower");
        RED_ROSE = (BlockFlowers)Block.REGISTRY.get("red_flower");
        BROWN_MUSHROOM = (BlockPlant)Block.REGISTRY.get("brown_mushroom");
        RED_MUSHROOM = (BlockPlant)Block.REGISTRY.get("red_mushroom");
        GOLD_BLOCK = (Block)Block.REGISTRY.get("gold_block");
        IRON_BLOCK = (Block)Block.REGISTRY.get("iron_block");
        DOUBLE_STEP = (BlockStepAbstract)Block.REGISTRY.get("double_stone_slab");
        STEP = (BlockStepAbstract)Block.REGISTRY.get("stone_slab");
        BRICK = (Block)Block.REGISTRY.get("brick_block");
        TNT = (Block)Block.REGISTRY.get("tnt");
        BOOKSHELF = (Block)Block.REGISTRY.get("bookshelf");
        MOSSY_COBBLESTONE = (Block)Block.REGISTRY.get("mossy_cobblestone");
        OBSIDIAN = (Block)Block.REGISTRY.get("obsidian");
        TORCH = (Block)Block.REGISTRY.get("torch");
        FIRE = (BlockFire)Block.REGISTRY.get("fire");
        MOB_SPAWNER = (Block)Block.REGISTRY.get("mob_spawner");
        WOOD_STAIRS = (Block)Block.REGISTRY.get("oak_stairs");
        CHEST = (BlockChest)Block.REGISTRY.get("chest");
        REDSTONE_WIRE = (BlockRedstoneWire)Block.REGISTRY.get("redstone_wire");
        DIAMOND_ORE = (Block)Block.REGISTRY.get("diamond_ore");
        DIAMOND_BLOCK = (Block)Block.REGISTRY.get("diamond_block");
        WORKBENCH = (Block)Block.REGISTRY.get("crafting_table");
        CROPS = (Block)Block.REGISTRY.get("wheat");
        SOIL = (Block)Block.REGISTRY.get("farmland");
        FURNACE = (Block)Block.REGISTRY.get("furnace");
        BURNING_FURNACE = (Block)Block.REGISTRY.get("lit_furnace");
        SIGN_POST = (Block)Block.REGISTRY.get("standing_sign");
        WOODEN_DOOR = (Block)Block.REGISTRY.get("wooden_door");
        LADDER = (Block)Block.REGISTRY.get("ladder");
        RAILS = (Block)Block.REGISTRY.get("rail");
        COBBLESTONE_STAIRS = (Block)Block.REGISTRY.get("stone_stairs");
        WALL_SIGN = (Block)Block.REGISTRY.get("wall_sign");
        LEVER = (Block)Block.REGISTRY.get("lever");
        STONE_PLATE = (Block)Block.REGISTRY.get("stone_pressure_plate");
        IRON_DOOR_BLOCK = (Block)Block.REGISTRY.get("iron_door");
        WOOD_PLATE = (Block)Block.REGISTRY.get("wooden_pressure_plate");
        REDSTONE_ORE = (Block)Block.REGISTRY.get("redstone_ore");
        GLOWING_REDSTONE_ORE = (Block)Block.REGISTRY.get("lit_redstone_ore");
        REDSTONE_TORCH_OFF = (Block)Block.REGISTRY.get("unlit_redstone_torch");
        REDSTONE_TORCH_ON = (Block)Block.REGISTRY.get("redstone_torch");
        STONE_BUTTON = (Block)Block.REGISTRY.get("stone_button");
        SNOW = (Block)Block.REGISTRY.get("snow_layer");
        ICE = (Block)Block.REGISTRY.get("ice");
        SNOW_BLOCK = (Block)Block.REGISTRY.get("snow");
        CACTUS = (Block)Block.REGISTRY.get("cactus");
        CLAY = (Block)Block.REGISTRY.get("clay");
        SUGAR_CANE_BLOCK = (Block)Block.REGISTRY.get("reeds");
        JUKEBOX = (Block)Block.REGISTRY.get("jukebox");
        FENCE = (Block)Block.REGISTRY.get("fence");
        PUMPKIN = (Block)Block.REGISTRY.get("pumpkin");
        NETHERRACK = (Block)Block.REGISTRY.get("netherrack");
        SOUL_SAND = (Block)Block.REGISTRY.get("soul_sand");
        GLOWSTONE = (Block)Block.REGISTRY.get("glowstone");
        PORTAL = (BlockPortal)Block.REGISTRY.get("portal");
        JACK_O_LANTERN = (Block)Block.REGISTRY.get("lit_pumpkin");
        CAKE_BLOCK = (Block)Block.REGISTRY.get("cake");
        DIODE_OFF = (BlockRepeater)Block.REGISTRY.get("unpowered_repeater");
        DIODE_ON = (BlockRepeater)Block.REGISTRY.get("powered_repeater");
        TRAP_DOOR = (Block)Block.REGISTRY.get("trapdoor");
        MONSTER_EGGS = (Block)Block.REGISTRY.get("monster_egg");
        SMOOTH_BRICK = (Block)Block.REGISTRY.get("stonebrick");
        BIG_MUSHROOM_1 = (Block)Block.REGISTRY.get("brown_mushroom_block");
        BIG_MUSHROOM_2 = (Block)Block.REGISTRY.get("red_mushroom_block");
        IRON_FENCE = (Block)Block.REGISTRY.get("iron_bars");
        THIN_GLASS = (Block)Block.REGISTRY.get("glass_pane");
        MELON = (Block)Block.REGISTRY.get("melon_block");
        PUMPKIN_STEM = (Block)Block.REGISTRY.get("pumpkin_stem");
        MELON_STEM = (Block)Block.REGISTRY.get("melon_stem");
        VINE = (Block)Block.REGISTRY.get("vine");
        FENCE_GATE = (Block)Block.REGISTRY.get("fence_gate");
        BRICK_STAIRS = (Block)Block.REGISTRY.get("brick_stairs");
        STONE_STAIRS = (Block)Block.REGISTRY.get("stone_brick_stairs");
        MYCEL = (BlockMycel)Block.REGISTRY.get("mycelium");
        WATER_LILY = (Block)Block.REGISTRY.get("waterlily");
        NETHER_BRICK = (Block)Block.REGISTRY.get("nether_brick");
        NETHER_FENCE = (Block)Block.REGISTRY.get("nether_brick_fence");
        NETHER_BRICK_STAIRS = (Block)Block.REGISTRY.get("nether_brick_stairs");
        NETHER_WART = (Block)Block.REGISTRY.get("nether_wart");
        ENCHANTMENT_TABLE = (Block)Block.REGISTRY.get("enchanting_table");
        BREWING_STAND = (Block)Block.REGISTRY.get("brewing_stand");
        CAULDRON = (BlockCauldron)Block.REGISTRY.get("cauldron");
        ENDER_PORTAL = (Block)Block.REGISTRY.get("end_portal");
        ENDER_PORTAL_FRAME = (Block)Block.REGISTRY.get("end_portal_frame");
        WHITESTONE = (Block)Block.REGISTRY.get("end_stone");
        DRAGON_EGG = (Block)Block.REGISTRY.get("dragon_egg");
        REDSTONE_LAMP_OFF = (Block)Block.REGISTRY.get("redstone_lamp");
        REDSTONE_LAMP_ON = (Block)Block.REGISTRY.get("lit_redstone_lamp");
        WOOD_DOUBLE_STEP = (BlockStepAbstract)Block.REGISTRY.get("double_wooden_slab");
        WOOD_STEP = (BlockStepAbstract)Block.REGISTRY.get("wooden_slab");
        COCOA = (Block)Block.REGISTRY.get("cocoa");
        SANDSTONE_STAIRS = (Block)Block.REGISTRY.get("sandstone_stairs");
        EMERALD_ORE = (Block)Block.REGISTRY.get("emerald_ore");
        ENDER_CHEST = (Block)Block.REGISTRY.get("ender_chest");
        TRIPWIRE_SOURCE = (BlockTripwireHook)Block.REGISTRY.get("tripwire_hook");
        TRIPWIRE = (Block)Block.REGISTRY.get("tripwire");
        EMERALD_BLOCK = (Block)Block.REGISTRY.get("emerald_block");
        SPRUCE_WOOD_STAIRS = (Block)Block.REGISTRY.get("spruce_stairs");
        BIRCH_WOOD_STAIRS = (Block)Block.REGISTRY.get("birch_stairs");
        JUNGLE_WOOD_STAIRS = (Block)Block.REGISTRY.get("jungle_stairs");
        COMMAND = (Block)Block.REGISTRY.get("command_block");
        BEACON = (BlockBeacon)Block.REGISTRY.get("beacon");
        COBBLE_WALL = (Block)Block.REGISTRY.get("cobblestone_wall");
        FLOWER_POT = (Block)Block.REGISTRY.get("flower_pot");
        CARROTS = (Block)Block.REGISTRY.get("carrots");
        POTATOES = (Block)Block.REGISTRY.get("potatoes");
        WOOD_BUTTON = (Block)Block.REGISTRY.get("wooden_button");
        SKULL = (Block)Block.REGISTRY.get("skull");
        ANVIL = (Block)Block.REGISTRY.get("anvil");
        TRAPPED_CHEST = (Block)Block.REGISTRY.get("trapped_chest");
        GOLD_PLATE = (Block)Block.REGISTRY.get("light_weighted_pressure_plate");
        IRON_PLATE = (Block)Block.REGISTRY.get("heavy_weighted_pressure_plate");
        REDSTONE_COMPARATOR_OFF = (BlockRedstoneComparator)Block.REGISTRY.get("unpowered_comparator");
        REDSTONE_COMPARATOR_ON = (BlockRedstoneComparator)Block.REGISTRY.get("powered_comparator");
        DAYLIGHT_DETECTOR = (BlockDaylightDetector)Block.REGISTRY.get("daylight_detector");
        REDSTONE_BLOCK = (Block)Block.REGISTRY.get("redstone_block");
        QUARTZ_ORE = (Block)Block.REGISTRY.get("quartz_ore");
        HOPPER = (BlockHopper)Block.REGISTRY.get("hopper");
        QUARTZ_BLOCK = (Block)Block.REGISTRY.get("quartz_block");
        QUARTZ_STAIRS = (Block)Block.REGISTRY.get("quartz_stairs");
        ACTIVATOR_RAIL = (Block)Block.REGISTRY.get("activator_rail");
        DROPPER = (Block)Block.REGISTRY.get("dropper");
        STAINED_HARDENED_CLAY = (Block)Block.REGISTRY.get("stained_hardened_clay");
        HAY_BLOCK = (Block)Block.REGISTRY.get("hay_block");
        WOOL_CARPET = (Block)Block.REGISTRY.get("carpet");
        HARDENED_CLAY = (Block)Block.REGISTRY.get("hardened_clay");
        COAL_BLOCK = (Block)Block.REGISTRY.get("coal_block");
        PACKED_ICE = (Block)Block.REGISTRY.get("packed_ice");
        ACACIA_STAIRS = (Block)Block.REGISTRY.get("acacia_stairs");
        DARK_OAK_STAIRS = (Block)Block.REGISTRY.get("dark_oak_stairs");
        DOUBLE_PLANT = (BlockTallPlant)Block.REGISTRY.get("double_plant");
        STAINED_GLASS = (BlockStainedGlass)Block.REGISTRY.get("stained_glass");
        STAINED_GLASS_PANE = (BlockStainedGlassPane)Block.REGISTRY.get("stained_glass_pane");
    }
}
