package net.minecraft.server.v1_7_R4;

public class Items
{
    public static final Item IRON_SPADE;
    public static final Item IRON_PICKAXE;
    public static final Item IRON_AXE;
    public static final Item FLINT_AND_STEEL;
    public static final Item APPLE;
    public static final ItemBow BOW;
    public static final Item ARROW;
    public static final Item COAL;
    public static final Item DIAMOND;
    public static final Item IRON_INGOT;
    public static final Item GOLD_INGOT;
    public static final Item IRON_SWORD;
    public static final Item WOOD_SWORD;
    public static final Item WOOD_SPADE;
    public static final Item WOOD_PICKAXE;
    public static final Item WOOD_AXE;
    public static final Item STONE_SWORD;
    public static final Item STONE_SPADE;
    public static final Item STONE_PICKAXE;
    public static final Item STONE_AXE;
    public static final Item DIAMOND_SWORD;
    public static final Item DIAMOND_SPADE;
    public static final Item DIAMOND_PICKAXE;
    public static final Item DIAMOND_AXE;
    public static final Item STICK;
    public static final Item BOWL;
    public static final Item MUSHROOM_SOUP;
    public static final Item GOLD_SWORD;
    public static final Item GOLD_SPADE;
    public static final Item GOLD_PICKAXE;
    public static final Item GOLD_AXE;
    public static final Item STRING;
    public static final Item FEATHER;
    public static final Item SULPHUR;
    public static final Item WOOD_HOE;
    public static final Item STONE_HOE;
    public static final Item IRON_HOE;
    public static final Item DIAMOND_HOE;
    public static final Item GOLD_HOE;
    public static final Item SEEDS;
    public static final Item WHEAT;
    public static final Item BREAD;
    public static final ItemArmor LEATHER_HELMET;
    public static final ItemArmor LEATHER_CHESTPLATE;
    public static final ItemArmor LEATHER_LEGGINGS;
    public static final ItemArmor LEATHER_BOOTS;
    public static final ItemArmor CHAINMAIL_HELMET;
    public static final ItemArmor CHAINMAIL_CHESTPLATE;
    public static final ItemArmor CHAINMAIL_LEGGINGS;
    public static final ItemArmor CHAINMAIL_BOOTS;
    public static final ItemArmor IRON_HELMET;
    public static final ItemArmor IRON_CHESTPLATE;
    public static final ItemArmor IRON_LEGGINGS;
    public static final ItemArmor IRON_BOOTS;
    public static final ItemArmor DIAMOND_HELMET;
    public static final ItemArmor DIAMOND_CHESTPLATE;
    public static final ItemArmor DIAMOND_LEGGINGS;
    public static final ItemArmor DIAMOND_BOOTS;
    public static final ItemArmor GOLD_HELMET;
    public static final ItemArmor GOLD_CHESTPLATE;
    public static final ItemArmor GOLD_LEGGINGS;
    public static final ItemArmor GOLD_BOOTS;
    public static final Item FLINT;
    public static final Item PORK;
    public static final Item GRILLED_PORK;
    public static final Item PAINTING;
    public static final Item GOLDEN_APPLE;
    public static final Item SIGN;
    public static final Item WOOD_DOOR;
    public static final Item BUCKET;
    public static final Item WATER_BUCKET;
    public static final Item LAVA_BUCKET;
    public static final Item MINECART;
    public static final Item SADDLE;
    public static final Item IRON_DOOR;
    public static final Item REDSTONE;
    public static final Item SNOW_BALL;
    public static final Item BOAT;
    public static final Item LEATHER;
    public static final Item MILK_BUCKET;
    public static final Item CLAY_BRICK;
    public static final Item CLAY_BALL;
    public static final Item SUGAR_CANE;
    public static final Item PAPER;
    public static final Item BOOK;
    public static final Item SLIME_BALL;
    public static final Item STORAGE_MINECART;
    public static final Item POWERED_MINECART;
    public static final Item EGG;
    public static final Item COMPASS;
    public static final ItemFishingRod FISHING_ROD;
    public static final Item WATCH;
    public static final Item GLOWSTONE_DUST;
    public static final Item RAW_FISH;
    public static final Item COOKED_FISH;
    public static final Item INK_SACK;
    public static final Item BONE;
    public static final Item SUGAR;
    public static final Item CAKE;
    public static final Item BED;
    public static final Item DIODE;
    public static final Item COOKIE;
    public static final ItemWorldMap MAP;
    public static final ItemShears SHEARS;
    public static final Item MELON;
    public static final Item PUMPKIN_SEEDS;
    public static final Item MELON_SEEDS;
    public static final Item RAW_BEEF;
    public static final Item COOKED_BEEF;
    public static final Item RAW_CHICKEN;
    public static final Item COOKED_CHICKEN;
    public static final Item ROTTEN_FLESH;
    public static final Item ENDER_PEARL;
    public static final Item BLAZE_ROD;
    public static final Item GHAST_TEAR;
    public static final Item GOLD_NUGGET;
    public static final Item NETHER_STALK;
    public static final ItemPotion POTION;
    public static final Item GLASS_BOTTLE;
    public static final Item SPIDER_EYE;
    public static final Item FERMENTED_SPIDER_EYE;
    public static final Item BLAZE_POWDER;
    public static final Item MAGMA_CREAM;
    public static final Item BREWING_STAND;
    public static final Item CAULDRON;
    public static final Item EYE_OF_ENDER;
    public static final Item SPECKLED_MELON;
    public static final Item MONSTER_EGG;
    public static final Item EXP_BOTTLE;
    public static final Item FIREBALL;
    public static final Item BOOK_AND_QUILL;
    public static final Item WRITTEN_BOOK;
    public static final Item EMERALD;
    public static final Item ITEM_FRAME;
    public static final Item FLOWER_POT;
    public static final Item CARROT;
    public static final Item POTATO;
    public static final Item POTATO_BAKED;
    public static final Item POTATO_POISON;
    public static final ItemMapEmpty MAP_EMPTY;
    public static final Item CARROT_GOLDEN;
    public static final Item SKULL;
    public static final Item CARROT_STICK;
    public static final Item NETHER_STAR;
    public static final Item PUMPKIN_PIE;
    public static final Item FIREWORKS;
    public static final Item FIREWORKS_CHARGE;
    public static final ItemEnchantedBook ENCHANTED_BOOK;
    public static final Item REDSTONE_COMPARATOR;
    public static final Item NETHER_BRICK;
    public static final Item QUARTZ;
    public static final Item MINECART_TNT;
    public static final Item MINECART_HOPPER;
    public static final Item HORSE_ARMOR_IRON;
    public static final Item HORSE_ARMOR_GOLD;
    public static final Item HORSE_ARMOR_DIAMOND;
    public static final Item LEASH;
    public static final Item NAME_TAG;
    public static final Item MINECART_COMMAND;
    public static final Item RECORD_1;
    public static final Item RECORD_2;
    public static final Item RECORD_3;
    public static final Item RECORD_4;
    public static final Item RECORD_5;
    public static final Item RECORD_6;
    public static final Item RECORD_7;
    public static final Item RECORD_8;
    public static final Item RECORD_9;
    public static final Item RECORD_10;
    public static final Item RECORD_11;
    public static final Item RECORD_12;
    
    static {
        IRON_SPADE = (Item)Item.REGISTRY.get("iron_shovel");
        IRON_PICKAXE = (Item)Item.REGISTRY.get("iron_pickaxe");
        IRON_AXE = (Item)Item.REGISTRY.get("iron_axe");
        FLINT_AND_STEEL = (Item)Item.REGISTRY.get("flint_and_steel");
        APPLE = (Item)Item.REGISTRY.get("apple");
        BOW = (ItemBow)Item.REGISTRY.get("bow");
        ARROW = (Item)Item.REGISTRY.get("arrow");
        COAL = (Item)Item.REGISTRY.get("coal");
        DIAMOND = (Item)Item.REGISTRY.get("diamond");
        IRON_INGOT = (Item)Item.REGISTRY.get("iron_ingot");
        GOLD_INGOT = (Item)Item.REGISTRY.get("gold_ingot");
        IRON_SWORD = (Item)Item.REGISTRY.get("iron_sword");
        WOOD_SWORD = (Item)Item.REGISTRY.get("wooden_sword");
        WOOD_SPADE = (Item)Item.REGISTRY.get("wooden_shovel");
        WOOD_PICKAXE = (Item)Item.REGISTRY.get("wooden_pickaxe");
        WOOD_AXE = (Item)Item.REGISTRY.get("wooden_axe");
        STONE_SWORD = (Item)Item.REGISTRY.get("stone_sword");
        STONE_SPADE = (Item)Item.REGISTRY.get("stone_shovel");
        STONE_PICKAXE = (Item)Item.REGISTRY.get("stone_pickaxe");
        STONE_AXE = (Item)Item.REGISTRY.get("stone_axe");
        DIAMOND_SWORD = (Item)Item.REGISTRY.get("diamond_sword");
        DIAMOND_SPADE = (Item)Item.REGISTRY.get("diamond_shovel");
        DIAMOND_PICKAXE = (Item)Item.REGISTRY.get("diamond_pickaxe");
        DIAMOND_AXE = (Item)Item.REGISTRY.get("diamond_axe");
        STICK = (Item)Item.REGISTRY.get("stick");
        BOWL = (Item)Item.REGISTRY.get("bowl");
        MUSHROOM_SOUP = (Item)Item.REGISTRY.get("mushroom_stew");
        GOLD_SWORD = (Item)Item.REGISTRY.get("golden_sword");
        GOLD_SPADE = (Item)Item.REGISTRY.get("golden_shovel");
        GOLD_PICKAXE = (Item)Item.REGISTRY.get("golden_pickaxe");
        GOLD_AXE = (Item)Item.REGISTRY.get("golden_axe");
        STRING = (Item)Item.REGISTRY.get("string");
        FEATHER = (Item)Item.REGISTRY.get("feather");
        SULPHUR = (Item)Item.REGISTRY.get("gunpowder");
        WOOD_HOE = (Item)Item.REGISTRY.get("wooden_hoe");
        STONE_HOE = (Item)Item.REGISTRY.get("stone_hoe");
        IRON_HOE = (Item)Item.REGISTRY.get("iron_hoe");
        DIAMOND_HOE = (Item)Item.REGISTRY.get("diamond_hoe");
        GOLD_HOE = (Item)Item.REGISTRY.get("golden_hoe");
        SEEDS = (Item)Item.REGISTRY.get("wheat_seeds");
        WHEAT = (Item)Item.REGISTRY.get("wheat");
        BREAD = (Item)Item.REGISTRY.get("bread");
        LEATHER_HELMET = (ItemArmor)Item.REGISTRY.get("leather_helmet");
        LEATHER_CHESTPLATE = (ItemArmor)Item.REGISTRY.get("leather_chestplate");
        LEATHER_LEGGINGS = (ItemArmor)Item.REGISTRY.get("leather_leggings");
        LEATHER_BOOTS = (ItemArmor)Item.REGISTRY.get("leather_boots");
        CHAINMAIL_HELMET = (ItemArmor)Item.REGISTRY.get("chainmail_helmet");
        CHAINMAIL_CHESTPLATE = (ItemArmor)Item.REGISTRY.get("chainmail_chestplate");
        CHAINMAIL_LEGGINGS = (ItemArmor)Item.REGISTRY.get("chainmail_leggings");
        CHAINMAIL_BOOTS = (ItemArmor)Item.REGISTRY.get("chainmail_boots");
        IRON_HELMET = (ItemArmor)Item.REGISTRY.get("iron_helmet");
        IRON_CHESTPLATE = (ItemArmor)Item.REGISTRY.get("iron_chestplate");
        IRON_LEGGINGS = (ItemArmor)Item.REGISTRY.get("iron_leggings");
        IRON_BOOTS = (ItemArmor)Item.REGISTRY.get("iron_boots");
        DIAMOND_HELMET = (ItemArmor)Item.REGISTRY.get("diamond_helmet");
        DIAMOND_CHESTPLATE = (ItemArmor)Item.REGISTRY.get("diamond_chestplate");
        DIAMOND_LEGGINGS = (ItemArmor)Item.REGISTRY.get("diamond_leggings");
        DIAMOND_BOOTS = (ItemArmor)Item.REGISTRY.get("diamond_boots");
        GOLD_HELMET = (ItemArmor)Item.REGISTRY.get("golden_helmet");
        GOLD_CHESTPLATE = (ItemArmor)Item.REGISTRY.get("golden_chestplate");
        GOLD_LEGGINGS = (ItemArmor)Item.REGISTRY.get("golden_leggings");
        GOLD_BOOTS = (ItemArmor)Item.REGISTRY.get("golden_boots");
        FLINT = (Item)Item.REGISTRY.get("flint");
        PORK = (Item)Item.REGISTRY.get("porkchop");
        GRILLED_PORK = (Item)Item.REGISTRY.get("cooked_porkchop");
        PAINTING = (Item)Item.REGISTRY.get("painting");
        GOLDEN_APPLE = (Item)Item.REGISTRY.get("golden_apple");
        SIGN = (Item)Item.REGISTRY.get("sign");
        WOOD_DOOR = (Item)Item.REGISTRY.get("wooden_door");
        BUCKET = (Item)Item.REGISTRY.get("bucket");
        WATER_BUCKET = (Item)Item.REGISTRY.get("water_bucket");
        LAVA_BUCKET = (Item)Item.REGISTRY.get("lava_bucket");
        MINECART = (Item)Item.REGISTRY.get("minecart");
        SADDLE = (Item)Item.REGISTRY.get("saddle");
        IRON_DOOR = (Item)Item.REGISTRY.get("iron_door");
        REDSTONE = (Item)Item.REGISTRY.get("redstone");
        SNOW_BALL = (Item)Item.REGISTRY.get("snowball");
        BOAT = (Item)Item.REGISTRY.get("boat");
        LEATHER = (Item)Item.REGISTRY.get("leather");
        MILK_BUCKET = (Item)Item.REGISTRY.get("milk_bucket");
        CLAY_BRICK = (Item)Item.REGISTRY.get("brick");
        CLAY_BALL = (Item)Item.REGISTRY.get("clay_ball");
        SUGAR_CANE = (Item)Item.REGISTRY.get("reeds");
        PAPER = (Item)Item.REGISTRY.get("paper");
        BOOK = (Item)Item.REGISTRY.get("book");
        SLIME_BALL = (Item)Item.REGISTRY.get("slime_ball");
        STORAGE_MINECART = (Item)Item.REGISTRY.get("chest_minecart");
        POWERED_MINECART = (Item)Item.REGISTRY.get("furnace_minecart");
        EGG = (Item)Item.REGISTRY.get("egg");
        COMPASS = (Item)Item.REGISTRY.get("compass");
        FISHING_ROD = (ItemFishingRod)Item.REGISTRY.get("fishing_rod");
        WATCH = (Item)Item.REGISTRY.get("clock");
        GLOWSTONE_DUST = (Item)Item.REGISTRY.get("glowstone_dust");
        RAW_FISH = (Item)Item.REGISTRY.get("fish");
        COOKED_FISH = (Item)Item.REGISTRY.get("cooked_fished");
        INK_SACK = (Item)Item.REGISTRY.get("dye");
        BONE = (Item)Item.REGISTRY.get("bone");
        SUGAR = (Item)Item.REGISTRY.get("sugar");
        CAKE = (Item)Item.REGISTRY.get("cake");
        BED = (Item)Item.REGISTRY.get("bed");
        DIODE = (Item)Item.REGISTRY.get("repeater");
        COOKIE = (Item)Item.REGISTRY.get("cookie");
        MAP = (ItemWorldMap)Item.REGISTRY.get("filled_map");
        SHEARS = (ItemShears)Item.REGISTRY.get("shears");
        MELON = (Item)Item.REGISTRY.get("melon");
        PUMPKIN_SEEDS = (Item)Item.REGISTRY.get("pumpkin_seeds");
        MELON_SEEDS = (Item)Item.REGISTRY.get("melon_seeds");
        RAW_BEEF = (Item)Item.REGISTRY.get("beef");
        COOKED_BEEF = (Item)Item.REGISTRY.get("cooked_beef");
        RAW_CHICKEN = (Item)Item.REGISTRY.get("chicken");
        COOKED_CHICKEN = (Item)Item.REGISTRY.get("cooked_chicken");
        ROTTEN_FLESH = (Item)Item.REGISTRY.get("rotten_flesh");
        ENDER_PEARL = (Item)Item.REGISTRY.get("ender_pearl");
        BLAZE_ROD = (Item)Item.REGISTRY.get("blaze_rod");
        GHAST_TEAR = (Item)Item.REGISTRY.get("ghast_tear");
        GOLD_NUGGET = (Item)Item.REGISTRY.get("gold_nugget");
        NETHER_STALK = (Item)Item.REGISTRY.get("nether_wart");
        POTION = (ItemPotion)Item.REGISTRY.get("potion");
        GLASS_BOTTLE = (Item)Item.REGISTRY.get("glass_bottle");
        SPIDER_EYE = (Item)Item.REGISTRY.get("spider_eye");
        FERMENTED_SPIDER_EYE = (Item)Item.REGISTRY.get("fermented_spider_eye");
        BLAZE_POWDER = (Item)Item.REGISTRY.get("blaze_powder");
        MAGMA_CREAM = (Item)Item.REGISTRY.get("magma_cream");
        BREWING_STAND = (Item)Item.REGISTRY.get("brewing_stand");
        CAULDRON = (Item)Item.REGISTRY.get("cauldron");
        EYE_OF_ENDER = (Item)Item.REGISTRY.get("ender_eye");
        SPECKLED_MELON = (Item)Item.REGISTRY.get("speckled_melon");
        MONSTER_EGG = (Item)Item.REGISTRY.get("spawn_egg");
        EXP_BOTTLE = (Item)Item.REGISTRY.get("experience_bottle");
        FIREBALL = (Item)Item.REGISTRY.get("fire_charge");
        BOOK_AND_QUILL = (Item)Item.REGISTRY.get("writable_book");
        WRITTEN_BOOK = (Item)Item.REGISTRY.get("written_book");
        EMERALD = (Item)Item.REGISTRY.get("emerald");
        ITEM_FRAME = (Item)Item.REGISTRY.get("item_frame");
        FLOWER_POT = (Item)Item.REGISTRY.get("flower_pot");
        CARROT = (Item)Item.REGISTRY.get("carrot");
        POTATO = (Item)Item.REGISTRY.get("potato");
        POTATO_BAKED = (Item)Item.REGISTRY.get("baked_potato");
        POTATO_POISON = (Item)Item.REGISTRY.get("poisonous_potato");
        MAP_EMPTY = (ItemMapEmpty)Item.REGISTRY.get("map");
        CARROT_GOLDEN = (Item)Item.REGISTRY.get("golden_carrot");
        SKULL = (Item)Item.REGISTRY.get("skull");
        CARROT_STICK = (Item)Item.REGISTRY.get("carrot_on_a_stick");
        NETHER_STAR = (Item)Item.REGISTRY.get("nether_star");
        PUMPKIN_PIE = (Item)Item.REGISTRY.get("pumpkin_pie");
        FIREWORKS = (Item)Item.REGISTRY.get("fireworks");
        FIREWORKS_CHARGE = (Item)Item.REGISTRY.get("firework_charge");
        ENCHANTED_BOOK = (ItemEnchantedBook)Item.REGISTRY.get("enchanted_book");
        REDSTONE_COMPARATOR = (Item)Item.REGISTRY.get("comparator");
        NETHER_BRICK = (Item)Item.REGISTRY.get("netherbrick");
        QUARTZ = (Item)Item.REGISTRY.get("quartz");
        MINECART_TNT = (Item)Item.REGISTRY.get("tnt_minecart");
        MINECART_HOPPER = (Item)Item.REGISTRY.get("hopper_minecart");
        HORSE_ARMOR_IRON = (Item)Item.REGISTRY.get("iron_horse_armor");
        HORSE_ARMOR_GOLD = (Item)Item.REGISTRY.get("golden_horse_armor");
        HORSE_ARMOR_DIAMOND = (Item)Item.REGISTRY.get("diamond_horse_armor");
        LEASH = (Item)Item.REGISTRY.get("lead");
        NAME_TAG = (Item)Item.REGISTRY.get("name_tag");
        MINECART_COMMAND = (Item)Item.REGISTRY.get("command_block_minecart");
        RECORD_1 = (Item)Item.REGISTRY.get("record_13");
        RECORD_2 = (Item)Item.REGISTRY.get("record_cat");
        RECORD_3 = (Item)Item.REGISTRY.get("record_blocks");
        RECORD_4 = (Item)Item.REGISTRY.get("record_chirp");
        RECORD_5 = (Item)Item.REGISTRY.get("record_far");
        RECORD_6 = (Item)Item.REGISTRY.get("record_mall");
        RECORD_7 = (Item)Item.REGISTRY.get("record_mellohi");
        RECORD_8 = (Item)Item.REGISTRY.get("record_stal");
        RECORD_9 = (Item)Item.REGISTRY.get("record_strad");
        RECORD_10 = (Item)Item.REGISTRY.get("record_ward");
        RECORD_11 = (Item)Item.REGISTRY.get("record_11");
        RECORD_12 = (Item)Item.REGISTRY.get("record_wait");
    }
}
